apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 7
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
